package com.municipalidad.localmix;
import android.app.*;import android.os.*;import android.Manifest;import android.content.pm.PackageManager;import android.widget.*;import android.view.*;
public class MainActivity extends Activity{
 LinearLayout list; EditText search; LibraryRepository repo; java.util.List<Track> tracks;
 public void onCreate(Bundle b){super.onCreate(b);repo=new LibraryRepository(this);ui();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_AUDIO},10);else refresh();}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,24,24,12);TextView h=new TextView(this);h.setText("LocalMix");h.setTextSize(30);r.addView(h);search=new EditText(this);search.setHint("Buscar canciones, artistas o álbumes");r.addView(search);LinearLayout n=new LinearLayout(this);Button home=new Button(this);home.setText("Inicio");Button lib=new Button(this);lib.setText("Biblioteca");Button pl=new Button(this);pl.setText("Listas +");n.addView(home);n.addView(lib);n.addView(pl);r.addView(n);ScrollView s=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);s.addView(list);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));lib.setOnClickListener(v->refresh());home.setOnClickListener(v->filter());pl.setOnClickListener(v->Toast.makeText(this,"Playlist local",Toast.LENGTH_SHORT).show());setContentView(r);}
 void refresh(){tracks=repo.scan();render(tracks);} void filter(){String q=search.getText().toString().toLowerCase();java.util.ArrayList<Track>x=new java.util.ArrayList<>();for(Track t:tracks)if(t.title.toLowerCase().contains(q)||t.artist.toLowerCase().contains(q)||t.album.toLowerCase().contains(q))x.add(t);render(x);}
 void render(java.util.List<Track>x){list.removeAllViews();for(Track t:x){TextView v=new TextView(this);v.setText(t.title+"\n"+t.artist+" • "+t.album);v.setTextSize(17);v.setPadding(0,18,0,18);v.setOnClickListener(z->Toast.makeText(this,"Preparando "+t.title,Toast.LENGTH_SHORT).show());list.addView(v);}}
}
